// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGkG3gj_dimz3FIWvBy_10DOXNURF1FjU',
    appId: '1:265131238364:web:908d3d5652cf8102082519',
    messagingSenderId: '265131238364',
    projectId: 'mywebsite-77193',
    authDomain: 'mywebsite-77193.firebaseapp.com',
    storageBucket: 'mywebsite-77193.firebasestorage.app',
    measurementId: 'G-DGJY68VC6W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrjigeXE2ycvqQR5YE_X6Qsr1GuWmEKoE',
    appId: '1:265131238364:android:ac5f235e05813fa3082519',
    messagingSenderId: '265131238364',
    projectId: 'mywebsite-77193',
    storageBucket: 'mywebsite-77193.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB6G0_1dHXKbbZcnVtNql3k6bZLOeWM04',
    appId: '1:265131238364:ios:84663db2295e9841082519',
    messagingSenderId: '265131238364',
    projectId: 'mywebsite-77193',
    storageBucket: 'mywebsite-77193.firebasestorage.app',
    iosBundleId: 'com.example.mywebsite',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB6G0_1dHXKbbZcnVtNql3k6bZLOeWM04',
    appId: '1:265131238364:ios:84663db2295e9841082519',
    messagingSenderId: '265131238364',
    projectId: 'mywebsite-77193',
    storageBucket: 'mywebsite-77193.firebasestorage.app',
    iosBundleId: 'com.example.mywebsite',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGkG3gj_dimz3FIWvBy_10DOXNURF1FjU',
    appId: '1:265131238364:web:ca072a87efea11b0082519',
    messagingSenderId: '265131238364',
    projectId: 'mywebsite-77193',
    authDomain: 'mywebsite-77193.firebaseapp.com',
    storageBucket: 'mywebsite-77193.firebasestorage.app',
    measurementId: 'G-8PSST496FD',
  );
}
